// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/customer/:id": {
    params: {
      "id": string;
    };
  };
  "/customer-create": {
    params: {};
  };
  "/customers": {
    params: {};
  };
  "/invitations": {
    params: {};
  };
  "/invite-customer": {
    params: {};
  };
  "/order/:orderID": {
    params: {
      "orderID": string;
    };
  };
  "/orders": {
    params: {};
  };
  "/product/add": {
    params: {};
  };
  "/product/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/products": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/settings/user/create": {
    params: {};
  };
  "/settings/user/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/settings/user/info": {
    params: {};
  };
  "/settings/users-list": {
    params: {};
  };
  "/actions/logout": {
    params: {};
  };
  "/actions/set-theme": {
    params: {};
  };
  "/api/locales/:lng/:ns": {
    params: {
      "lng": string;
      "ns": string;
    };
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/customer/:id" | "/customer-create" | "/customers" | "/invitations" | "/invite-customer" | "/order/:orderID" | "/orders" | "/product/add" | "/product/edit/:id" | "/products" | "/settings" | "/settings/user/create" | "/settings/user/edit/:id" | "/settings/user/info" | "/settings/users-list" | "/actions/logout" | "/actions/set-theme" | "/api/locales/:lng/:ns" | "/login";
  };
  "routes/__main/__layout.tsx": {
    id: "routes/__main/__layout";
    page: "/customer/:id" | "/customer-create" | "/customers" | "/" | "/invitations" | "/invite-customer" | "/order/:orderID" | "/orders" | "/product/add" | "/product/edit/:id" | "/products" | "/settings" | "/settings/user/create" | "/settings/user/edit/:id" | "/settings/user/info" | "/settings/users-list";
  };
  "routes/__main/customer/$id/index.tsx": {
    id: "routes/__main/customer/$id/index";
    page: "/customer/:id";
  };
  "routes/__main/customer-create/index.tsx": {
    id: "routes/__main/customer-create/index";
    page: "/customer-create";
  };
  "routes/__main/customers/index.tsx": {
    id: "routes/__main/customers/index";
    page: "/customers";
  };
  "routes/__main/index/index.tsx": {
    id: "routes/__main/index/index";
    page: "/";
  };
  "routes/__main/invitations/route.tsx": {
    id: "routes/__main/invitations/route";
    page: "/invitations";
  };
  "routes/__main/invite-customer/index.tsx": {
    id: "routes/__main/invite-customer/index";
    page: "/invite-customer";
  };
  "routes/__main/order/$orderID/index.tsx": {
    id: "routes/__main/order/$orderID/index";
    page: "/order/:orderID";
  };
  "routes/__main/orders/index.tsx": {
    id: "routes/__main/orders/index";
    page: "/orders";
  };
  "routes/__main/product/add/index.tsx": {
    id: "routes/__main/product/add/index";
    page: "/product/add";
  };
  "routes/__main/product/edit/$id/index.tsx": {
    id: "routes/__main/product/edit/$id/index";
    page: "/product/edit/:id";
  };
  "routes/__main/products/index.tsx": {
    id: "routes/__main/products/index";
    page: "/products";
  };
  "routes/__main/settings/__layout.tsx": {
    id: "routes/__main/settings/__layout";
    page: "/settings" | "/settings/user/create" | "/settings/user/edit/:id" | "/settings/user/info" | "/settings/users-list";
  };
  "routes/__main/settings/index/index.tsx": {
    id: "routes/__main/settings/index/index";
    page: "/settings";
  };
  "routes/__main/settings/user/create/index.tsx": {
    id: "routes/__main/settings/user/create/index";
    page: "/settings/user/create";
  };
  "routes/__main/settings/user/edit/$id/index.tsx": {
    id: "routes/__main/settings/user/edit/$id/index";
    page: "/settings/user/edit/:id";
  };
  "routes/__main/settings/user/info/index.tsx": {
    id: "routes/__main/settings/user/info/index";
    page: "/settings/user/info";
  };
  "routes/__main/settings/users-list/index.tsx": {
    id: "routes/__main/settings/users-list/index";
    page: "/settings/users-list";
  };
  "routes/actions/logout/index.tsx": {
    id: "routes/actions/logout/index";
    page: "/actions/logout";
  };
  "routes/actions/set-theme/index.ts": {
    id: "routes/actions/set-theme/index";
    page: "/actions/set-theme";
  };
  "routes/api/locales/$lng/$ns/index.ts": {
    id: "routes/api/locales/$lng/$ns/index";
    page: "/api/locales/:lng/:ns";
  };
  "routes/login/index.tsx": {
    id: "routes/login/index";
    page: "/login";
  };
};